### ISSUE TITLE
Recommanded modules not installed

### ISSUE THREAD

**Issue by marionf** [PrestaShop/ps_mbo#17]
MBO module is installed

Go on Shipping > carriers
Install a recommanded module like mondial relay
You are redirected to installed modules tab instead of the configuration of the module & the module isn't installed

Now, click on "recommanded modules" in the header of the carriers' page
Install a recommanded module like mondial relay
You are redirected to installed modules tab instead of the configuration of the module & the module isn't installed

**Comment by MrBaiame** [comment]
I thought it was a core issue ?

**Comment by marionf** [comment]
Yes, right !
