### ISSUE TITLE
Display issue on the header BO

### ISSUE THREAD

**Issue by marionf** [PrestaShop/ps_mbo#25]
With MBO the header is broken

![capture d ecran_57](https://user-images.githubusercontent.com/13449658/42748285-eecb73ca-88df-11e8-9867-47eb968f5b14.png)

Without MBO, it looks like better:

![capture d ecran_56](https://user-images.githubusercontent.com/13449658/42748298-fc4535e0-88df-11e8-93fb-9af1d1683790.png)

**Comment by MrBaiame** [comment]
#26 fixes the issue. The general problem is that the theme css loaded aren't the same between a module page and a symfony page, that means there are a few differences, the real fix would be to have this new css loaded no matter what

**Comment by marionf** [comment]
Fixed
