### ISSUE TITLE
Design issue of module catalog page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/ps_mbo#27]
Following this PR: https://github.com/PrestaShop/PrestaShop/pull/9287
The buttons of the module catalog page with MBO are not very pretty

![capture d ecran_177](https://user-images.githubusercontent.com/13449658/44342352-f9e86800-a48a-11e8-8ae6-dc49ff09ef81.png)

![capture d ecran_178](https://user-images.githubusercontent.com/13449658/44342353-f9e86800-a48a-11e8-9d74-b0693e068a93.png)

Also, when I click on Disable/Disable mobile, the button should change for Enable/Enable mobile

![mbo-pr9287](https://user-images.githubusercontent.com/13449658/44342471-65cad080-a48b-11e8-8853-a1bf4c0c1b1c.gif)

And, the number of notifications are not ok

![capture d ecran_277](https://user-images.githubusercontent.com/13449658/45105919-b140d800-b135-11e8-9fb9-bd5be4ffa5fc.png)

**Comment by MrBaiame** [comment]
Shouldn't it be something the core team needs to do if they changed it ?

**Comment by marionf** [comment]
@eternoendless What do you think ?

**Comment by Quetzacoalt91** [comment]
The PR has not been merged yet, but you can find the changes to copy on the core here: https://github.com/PrestaShop/PrestaShop/pull/9287/files#diff-8ce12f544e70f168b80a09e88b3391d5R35

**Comment by marionf** [comment]
I still have this issue 

![capture d ecran_314](https://user-images.githubusercontent.com/13449658/45954820-61f01800-c00e-11e8-8f87-bc1be39d706d.png)

**Comment by marionf** [comment]
Fixed
