### ISSUE TITLE
Impossibility to Scroll the menu when MBO is installed

### ISSUE THREAD

**Issue by LouToma** [PrestaShop/ps_mbo#34]
Page Theme catalog ![sansmbo](https://user-images.githubusercontent.com/13449462/45496134-094e8e80-b775-11e8-870a-1f5807c94823.png)
- Without MBO it's possible to scroll the menu, this functionnality disappears when MBO is installed.
- in the search window : its said "search" instead of ""search (eg product).... see the screenshot on comment window
- The "fil d'ariane" colour is not right : it should be dark but it's grey. see the screenshot on comment window "Design" is grey and not dark

**Comment by mbadrani** [comment]
with MBO
![image](https://user-images.githubusercontent.com/29543279/45497899-2c7b3d00-b779-11e8-8681-0fc5f92f26c8.png)


without MBO
![image](https://user-images.githubusercontent.com/29543279/45497944-4157d080-b779-11e8-8560-a75d3e675916.png)

**Comment by MrBaiame** [comment]
I can scroll, i can't reproduce the issue.

The only string i can change is the tab name which is currently 'Theme catalog', if I have to change it, tell me.

**Comment by LouToma** [comment]
Ok.
@Quetzacoalt91 can you reproduce the issue by any chance ?

**Comment by mbadrani** [comment]
Alexis just told me that this occurs because of the displaying of the debug_mode toolbar
