### ISSUE TITLE
debug_mode toolbar no more displayed in Theme Catalog page

### ISSUE THREAD

**Issue by mbadrani** [PrestaShop/ps_mbo#35]
When you access to the "Design > Theme Catalog" page, you should see the Debug_mode toolbar on the footer (currently the behaviour on the 1.7.5.0 version)

**Comment by MrBaiame** [comment]
the toolbar appears only on symfony controllers, it doesn't appear on legacy controller neither

**Comment by mbadrani** [comment]
so how do you explain this ...
without MBO
![image](https://user-images.githubusercontent.com/29543279/45498934-8a108900-b77b-11e8-9050-b0fffe290a14.png)

with MBO
![image](https://user-images.githubusercontent.com/29543279/45498960-9b599580-b77b-11e8-835a-345472d603d9.png)

**Comment by PierreRambaud** [comment]
The Symfony Debug toolbar only appears on Symfony pages. Because Mbo is a module and not a Symfony page, it's logic he doesn't have one.
I close this issue.
