### ISSUE TITLE
Old "help" button on the Design > theme catalog (design and content)

### ISSUE THREAD

**Issue by mbadrani** [PrestaShop/ps_mbo#37]
If we compare the two Help buttons:

without MBO
![image](https://user-images.githubusercontent.com/29543279/45496868-aeb63200-b776-11e8-9579-0b010600e0fd.png)
when we click on it
![image](https://user-images.githubusercontent.com/29543279/45496900-b970c700-b776-11e8-9a91-12910634cf87.png)

with MBO
![image](https://user-images.githubusercontent.com/29543279/45496925-c392c580-b776-11e8-876f-fc2d5d1ec116.png)
when we click on it
![image](https://user-images.githubusercontent.com/29543279/45496949-cee5f100-b776-11e8-99cf-aeb95e466ecc.png)

**Comment by MrBaiame** [comment]
same thing, it's the difference between legacy and symfony controllers

**Comment by mbadrani** [comment]
So with MBO you've migrated this page?

**Comment by PierreRambaud** [comment]
MBO is a module, not a Symfony page. 
I close this issue, it's not related to the module.
