### ISSUE TITLE
Logos broken on Shipping > carriers "recommended modules and services"

### ISSUE THREAD

**Issue by mbadrani** [PrestaShop/ps_mbo#38]
Without MBO

![image](https://user-images.githubusercontent.com/29543279/45498647-cdb6c300-b77a-11e8-9051-fab19631e519.png)

With MBO

![image](https://user-images.githubusercontent.com/29543279/45498671-db6c4880-b77a-11e8-9884-56f499bb1e8b.png)

**Comment by MrBaiame** [comment]
https://github.com/PrestaShop/ps_mbo/commit/b1e62b64e2e7ca974f9b3a44cea8085f0d6a2d58

Fixes the issue
