### ISSUE TITLE
No .gitignore

### ISSUE THREAD

**Issue by matks** [PrestaShop/ps_mbo#39]
You need a .gitignore to ignore composer-generated files in `vendor` folder

**Comment by LouToma** [comment]
@matks Needs to be fixed ?

**Comment by matks** [comment]
This is a "nice to have" only but this makes the task of developers a lot easier.

It should contain at least
```
vendor/
.idea
.DS_Store
```

And either it should `composer.lock` either the `composer.lock` file should be committed in git

**Comment by MrBaiame** [comment]
Fixed by another PR
