### ISSUE TITLE
Filter issue on catalog page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/ps_mbo#40]
Go on Module Catalog page
Select a category (Promotions & Marketing for example)
You should have 24 results
Try to sort by Increasing price/Decreasing price/Name or Popularity
You have lost the selected category and have all modules displayed
We should have only the modules sorted for the selected category like in 1.7.4.2

Same thing if I select a category and enter something in the search bar, it should search only in the selected category

**Comment by MrBaiame** [comment]
Are we sure we want to do that ? I thought that removing the filter was made on purpose ?

**Comment by marionf** [comment]
I think it's regression, it didn't work like that in 1.7.4.2 or 1.7.5.0 without MBO

**Comment by LouToma** [comment]
@MrBaiame where did you see you should remove the filter ? Once again,  the behaviour must remain the same as before

**Comment by marionf** [comment]
Fixed by #51
