### ISSUE TITLE
Design issue on Module Catalog after installing a module

### ISSUE THREAD

**Issue by marionf** [PrestaShop/ps_mbo#48]
Design issue on Module Catalog after installing a module

![capture d ecran_342](https://user-images.githubusercontent.com/13449658/46132497-6ef34e00-c23e-11e8-8299-46b5b34076e0.png)

**Comment by MrBaiame** [comment]
I can not reproduce this issue, on what branch are you testing ?

**Comment by marionf** [comment]
I am on dev branch

**Comment by MrBaiame** [comment]
As seen together, I've merged every modifications, please tell me if you can still reproduce the issue :)

**Comment by MrBaiame** [comment]
https://github.com/PrestaShop/ps_mbo/pull/50
