### ISSUE TITLE
Bad link Module Manager page

### ISSUE THREAD

**Issue by marionf** [PrestaShop/ps_mbo#49]
MBO is installed

I am on module Manager page, when I click on a category link it's the link of the core page instead of MBO page

![capture d ecran_345](https://user-images.githubusercontent.com/13449658/46135336-3c008880-c245-11e8-8025-6a72bd39f75a.png)

Same thing for quick access

![capture d ecran_348](https://user-images.githubusercontent.com/13449658/46145708-46308000-c261-11e8-9f65-92f6ec6a0ee9.png)

**Comment by LouToma** [comment]
@PierreRambaud I'm pretty sure we tested and it was ok ?

**Comment by PierreRambaud** [comment]
@LouToma Yes we tested this without MBO. Not sure Mbo includes change to override this part.

**Comment by LouToma** [comment]
Can you meet @PierreRambaud & @MrBaiame to find a way?

**Comment by marionf** [comment]
@Quetzacoalt91 Oh yes, my bad :)

**Comment by marionf** [comment]
@MrBaiame 

It's ok for the link but when I click on it and arrive on Module Catalog, the category isn't selected in the drop-down menu
And, for exemple, I click on Promo & Marketing, 1 module is displayed.
If I click on Promo & Marketing in the drop-down, 2 modules are displayed.

Screenrecord: https://drive.google.com/open?id=10pVMx5b7jKWb4rWOgmfThBAKnkJ8eIVT

**Comment by marionf** [comment]
@MrBaiame 

It's ok when I click on a link on Module Manager page :+1: 

But now, when I am on Module Catalog and select a category, it's not selected in the drop-down

![capture d ecran_396](https://user-images.githubusercontent.com/13449658/46543487-495ee800-c8c1-11e8-9d97-54718c73711a.png)

**Comment by MrBaiame** [comment]
Should be fix now @marionf

**Comment by marionf** [comment]
Fixed
