### ISSUE TITLE
Display issue on module catalog tab after install

### ISSUE THREAD

**Issue by marionf** [PrestaShop/ps_mbo#5]
@MrBaiame 

On module catalog tab, I have a display issue after installing a module

![capture du 2018-06-07 18-14-38](https://user-images.githubusercontent.com/13449658/41112279-d0853bfa-6a7e-11e8-80d1-2c150a3aa3f1.png)

I don't have it on Selection tab

![capture du 2018-06-07 18-09-05](https://user-images.githubusercontent.com/13449658/41112319-e5a470f0-6a7e-11e8-80ad-d73fdd57ad71.png)

**Comment by MrBaiame** [comment]
So we shouldn't display something after the module is installed ?

**Comment by marionf** [comment]
It's about the Configure button

![capture du 2018-06-07 18-14-38](https://user-images.githubusercontent.com/13449658/41151134-31b2377a-6b10-11e8-8148-b01754f12d46.png)
