### ISSUE TITLE
Confirgure a module installed by zip doesn't work

### ISSUE THREAD

**Issue by marionf** [PrestaShop/ps_mbo#54]
Install MBO
Click on Module Catalog
Upload a module by zip
Click on Configure button

![capture d ecran_399](https://user-images.githubusercontent.com/13449658/46598097-0f6d2c00-cae3-11e8-8b7f-01104f99b5dc.png)

![capture d ecran_398](https://user-images.githubusercontent.com/13449658/46598101-1300b300-cae3-11e8-891c-9c80c79d0004.png)

**Comment by marionf** [comment]
Fixed

**Comment by marionf** [comment]
@MrBaiame this issue is back again with the last version

**Comment by MrBaiame** [comment]
On which branch did you test ? it works on master

**Comment by marionf** [comment]
I was on dev branch
