### ISSUE TITLE
Module Catalog - Click on the "Read more" link => Exception

### ISSUE THREAD

**Issue by khouloudbelguith** [PrestaShop/ps_mbo#72]
Hi,

PS1.7.5.x
In the BO => Modules => Module Catalog => when we click on the "read more" link, after some seconds of reloading we have an error displayed
![image](https://user-images.githubusercontent.com/16067358/49439039-49e00600-f7c0-11e8-995e-75fa481352de.png)
![image](https://user-images.githubusercontent.com/16067358/49439045-4d738d00-f7c0-11e8-93e3-e663a0be54a8.png)

When mbo module not installed there are no errors.
Related to https://github.com/PrestaShop/ps_mbo/issues/42

Thanks!

**Comment by marionf** [comment]
Fixed with https://github.com/PrestaShop/ps_mbo/commit/8ecb7a99442a7ef38bd2ffafbd1a19ff14956873
