### ISSUE TITLE
CTA button is outside the box

### ISSUE THREAD

**Issue by LouToma** [PrestaShop/ps_mbo#73]
Click on Module Catalog
On AdminPsMboModule with v1.1.0 version, CTA button is displayed outside the box

![image](https://user-images.githubusercontent.com/13449462/49457404-14044700-f7eb-11e8-9bec-5b33f8e467bb.png)

**Comment by marionf** [comment]
@LouToma issue with CTA button was already reported here #68 and it's fixed by #70

**Comment by Shiryu75** [comment]
Are you sure ? Because i've tested this (screenshot is mine) on a fresh Nightly build 1.7.5, with my module (Ready Tips) with mbo 1.1.0 and i cleared the cache several times to make sure.
