### ISSUE TITLE
bad display of special chars like &

### ISSUE THREAD

**Issue by marionf** [PrestaShop/ps_mbo#74]
![capture d ecran_720](https://user-images.githubusercontent.com/13449658/49517148-bb40b700-f89b-11e8-8908-ba7832781e0f.png)

**Comment by MrBaiame** [comment]
I don't have any issue like this, are you able to reproduce it @marionf  ?

**Comment by marionf** [comment]
Yes, I can reproduce it, I send you the module in private

**Comment by MrBaiame** [comment]
I have the same issue with or without MBO installed, it's either an issue with what the core sends back, or with the encoding of the module file

**Comment by Shiryu75** [comment]
File's encoded in UTF-8

**Comment by MrBaiame** [comment]
Then I'd say it's what the core sends back

**Comment by marionf** [comment]
@MrBaiame 

I don't have this issue without MBO

![capture d ecran_719](https://user-images.githubusercontent.com/13449658/49517054-79b00c00-f89b-11e8-9a4c-39059e9dd21e.png)

**Comment by Shiryu75** [comment]
Shall I rename the module OnBoarding And Tips ? :)

**Comment by marionf** [comment]
Fixed with https://github.com/PrestaShop/ps_mbo/commit/641e9a0ee20eb95718cad54dc1b264082ee61964
